
version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./test.db:/app/test.db
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./test.db
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
      - ALLOWED_ORIGINS=http://localhost:5173,http://localhost:5174,http://localhost:3000
    restart: unless-stopped
